### ISSUE TITLE
Plots tab not updated

### ISSUE THREAD

**Issue by hernanmd** [rakki-18/Matrix-Benchmarks#17]
How to reproduce:

1. Run "Accessing a cell in a matrix" Single benchmarks.
2. Access the Plots tab.
3. Go back to Single benchmarks tab.
4. Select "Matrix multiplication" benchmark item.
5. Run it.
6. Plots tab are not updated with new benchmark results plots.

**Comment by rakki-18** [comment]
@hernanmd Thank you for opening up the issue.
I tried reproducing the issue [here](https://drive.google.com/file/d/10t82vJYFVxHbHDusSS9CD2-Us9I8hONB/view?usp=sharing). But, there don't seem to be any errors for me. Could you please check the video once?
